### ISSUE TITLE
API requires a site url

### ISSUE THREAD

**Issue by Adam-Collier** [netlify/gotell#12]
A potential bug, currently getting this error when trying to deploy the API to Zeit" `msg="Error verifying settings: API requires a site url"`

I have tried setting the gotell environment variables in now.json, now secret command and .env file with no success. I've also tried adding it to CMD in the dockerfile but again the error persisted. I'm not sure whether this is a Zeit issue or there is a bug in the code

![image](https://user-images.githubusercontent.com/20065745/42901830-9244807e-8ac4-11e8-98f1-6b0dbdbd9c78.png)

**Comment by thepeted** [comment]
I am experiencing the same issue (running locally)

Dockerfile:
```
FROM calavera/go-glide:v0.12.2

ADD . /go/src/github.com/netlify/gotell

RUN useradd -m netlify && cd /go/src/github.com/netlify/gotell && make deps build && mv gotell /usr/local/bin/

ENV GOTELL_SITE_URL https://myapp.netlify.com
ENV GOTELL_REPOSITORY me/my_repo
ENV GOTELL_ACCESS_TOKEN 999

USER netlify
CMD ["gotell"]
```

Output:
```
> docker run gotell-thing:latest
time="2018-07-18T21:31:45Z" level=fatal msg="Error verifying settings: API requires a site url"
```
